AbanteAI/mentat

.github/workflows/lint_and_test.yml, tests/license_check.py
add automatic license check to github actions
=> License check

mentat/code_file_manager.py
=> Fix typo in code_file_manager.py

mentat/code_file_manager.py, tests/code_file_manager_test.py
=> Encoding bug fix

mentat/app.py, mentat/code_file_manager.py, mentat/git_handler.py, tests/code_file_manager_test.py, tests/git_handler_test.py
Move git root handling outside of code_file_manager
=> Git migration

.gitignore, docs/configuration.md, mentat/app.py, mentat/config_manager.py, mentat/git_handler.py, mentat/llm_api.py, tests/code_file_manager_test.py, tests/config_test.py, tests/conftest.py
Change config name to .mentat_config.json and allow project specific config
=> The great config migration

mentat/llm_api.py, setup.py
I wasn't able to replicate, but this might fix: https://github.com/biobootloader/mentat/issues/34
=> Fix tiktoken crash

mentat/code_change.py, tests/code_change_test.py
Without this I'm getting:
```
File "/Volumes/workbench/biobootloader/mentat/mentat/code_change.py", line 77, in __init__
self.first_changed_line - 1
~~~~~~~~~~~~~~~~~~~~~~~~^~~
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```
https://github.com/biobootloader/mentat/blob/c91548cd4d2f45e944428c79e28a71091431641d/mentat/code_change.py#L77
I don't have a good test case, sorry, just had time for a quick PR.
=> Fix a type mismatch

mentat/change_conflict_resolution.py, mentat/code_change.py, mentat/code_file_manager.py, mentat/parsing.py
=> Refactor: keep git_root private to CodeFileManager

tests/benchmark_test.py
=> Fix `test_start_project_from_scratch`

.github/workflows/lint_and_test.yml, mentat/app.py, mentat/change_conflict_resolution.py, mentat/code_change.py, mentat/code_change_display.py, mentat/code_context.py, mentat/code_file.py, mentat/code_file_manager.py, mentat/code_map.py, mentat/commands.py, mentat/config_manager.py, mentat/conversation.py, mentat/errors.py, mentat/git_handler.py, mentat/llm_api.py, mentat/mentat_prompt_session.py, mentat/parsing.py, mentat/streaming_printer.py, mentat/user_input_manager.py, pyrightconfig.json, requirements.txt, tests/config_test.py, tests/conftest.py, tests/git_handler_test.py, tests/license_check.py, tests/measure_api_speed.py
This PR adds [pyright](https://github.com/microsoft/pyright), a static type checker, as a dependency and type checks code with Github Actions.
The goal of this is to make it development and contributing easier. With enforced type checking you get:
- Fewer errors in your code. Static type checking helps catch a lot of errors prior to runtime
- Better readability. Seeing the argument and return types for everything makes understanding someone else's code way easier.
- Better editor/LSP completions. Properly typed python code makes intellisense for VSCode or whatever editor you use work way better
Right now we have a bunch of type checking errors that will cause the CI/CD build step to fail. If we want to add pyright support, I think we should fix those typing errors in this PR.
=> Add pyright

tests/benchmark_test.py
Refactors the benchmarks to make it easier to make new benchmarks; I ran every benchmark a few times to confirm that they all can still pass.
=> refactor benchmarks

mentat/code_context.py, mentat/code_file.py, mentat/code_file_manager.py, tests/code_file_manager_test.py
Addresses #93, test that you can run mentat from a subdirectory of your `git_root`, and pass in paths relative to your `pwd`:
- One small fix in `code_file_manager` to make it work as described
- One new test in `code_file_manager_test` to confirm it works
=> Test run in subdirectory

mentat/code_context.py, mentat/commands.py, mentat/mentat_prompt_session.py, tests/commands_test.py
This PR adds commands for adding and removing files/partial files from the code context.
What isn't covered here that I'm including in additional PRs:
- update code tree w/ out-of-repo files
- add commands inputs to history completions
- fix completions for /add command to show files
- add command to print code map
- add command to list context files
- handle going over context with added files
- add (fuzzy) completions for /remove command
- merge/remove partial files
=> add /add and /remove commands

mentat/app.py, mentat/code_file_manager.py, mentat/diff_context.py, mentat/git_handler.py, pyproject.toml, tests/code_file_manager_test.py, tests/conftest.py, tests/diff_context_test.py
Optionally add the diff of a commit or branch to the system prompt. Goes with #81
=> Diff context

docs/configuration.md, mentat/app.py, mentat/code_map.py, mentat/config_manager.py, mentat/conversation.py, mentat/default_config.json, mentat/llm_api.py, tests/conftest.py
Users can set which model to use. If it's not a GPT-4 model warnings are given. If it is a non-deprecated OpenAI model costs and tokens are computed. How to use an alternative API endpoint is documented.
=> Model configuration

docs/configuration.md, mentat/app.py, mentat/code_context.py, mentat/conversation.py, mentat/parsers/block_parser.py, mentat/parsers/change_display_helper.py, mentat/parsers/parser.py, mentat/parsers/replacement_parser.py, mentat/parsers/split_diff_parser.py, mentat/prompts/split_diff_parser_prompt.txt, tests/code_file_manager_test.py, tests/parser_tests/split_diff_format_error_test.py, tests/parser_tests/split_diff_format_test.py
Add a split diff parser with a format of:
\<\<\<\<\<\< HEAD
removed lines
\=\=\=\=\=\=\=
added lines
\>\>\>\>\>\>\> updated
=> add split diff parser and tests

mentat/code_map.py, mentat/utils.py
This PR adds a function that wraps async subprocess calls. 
I don't think we should make all the synchronous subprocesses calls async here, better to do that separately imo.
=> add util func for async subprocess

tests/benchmarks/exercism_practice.py, tests/conftest.py
Quick quality of life feature.
=> Flag to choose exercism exercises

tests/benchmarks/exercism_practice.py
We were not awaiting input requested in the right place so we could sometimes run the tests before mentat had edited the files.
=> Exercism fix

mentat/llm_api.py, mentat/logging_config.py, mentat/session.py, mentat/session_input.py, mentat/terminal/client.py, tests/benchmarks/exercism_practice.py
Fixes some problems with the current logging setup we had
=> remove basicConfig and modify the root handler directly

tests/benchmarks/exercise_runners/abstract_exercise_runner.py, tests/benchmarks/exercise_runners/exercise_runner_factory.py, tests/benchmarks/exercise_runners/javascript_exercise_runner.py, tests/benchmarks/exercise_runners/python_exercise_runner.py, tests/benchmarks/exercism_practice.py
Language specific code, really all the code needed to run an exercise, is put in ExerciseRunners. Also two misc clean ups:
* String concatenation is used instead of """. Previously there were incorrect line breaks in prompts.
* Un-ran tests return a different dictionary which isn't written to results.txt.
=> Exercism language refactor

tests/benchmarks/exercism_benchmark.html, tests/benchmarks/exercism_practice.py
I noticed 2 small bugs in the benchmarks that slipped through my previous PR. @jakethekoenig if you could approve and merge that would be great!
=> fix small bugs

mentat/broadcast.py, mentat/terminal/client.py
Fixes #146, broadcast now holds events until there is a subscriber. Would especially love @waydegg's feedback on this. Merge after #143, only the last commit belongs to this PR.
=> Broadcast hold events

mentat/code_context.py, mentat/code_file.py, mentat/conversation.py, mentat/embeddings.py, mentat/llm_api.py, mentat/python_client/client.py, mentat/session.py, mentat/terminal/client.py, requirements.txt, tests/benchmarks/context_benchmark.py, tests/benchmarks/exercism_practice.py, tests/benchmarks/utils.py, tests/code_context_test.py, tests/code_file_manager_test.py, tests/embeddings_test.py
A basic implementation of embeddings and context-generation benchmarks. This is a barebones implementation, off by default, to be built on in future PRs.
- `llm_api.call_embedding_api`
- `embeddings.get_feature_similarity_scores(prompt, features)`: returns a list of scores for the given features (CodeFiles) based on their embedding similarity to a prompt. This can be used for context-generation or search.
- `EmbeddingsDatabase`, saved to .mentat/embeddings.json.gz, which is just {checksum: embedding} pairs.
- `CodeContext.settings.no_embeddings`, which is True (so no embeddings) by default.
- A new terminal arg `--embedding` to activate embeddings, and fill your remaining context with the most relevant files.
There are some notes at the top of `tests/benchmarks/context_benchmark.py`. …
=> Embeddings

.gitignore, pyproject.toml
This should have been included in #144
=> add benchmark repos to .gitignore

mentat/errors.py, mentat/session.py, mentat/session_input.py, tests/conftest.py
Fixes #148. What does everyone think of the SessionExit as a way to quit the session? It will only work from within the _main coroutine of the session, and I'm not entirely sure I like using an exception to quit, but it is fairly easy and simple.
=> add way to exit main session loop, add command catching and quitting to sessioninput

MANIFEST.in, mentat/conversation.py, setup.py
=> use graft instead of recursive-include

mentat/code_context.py, mentat/include_files.py, tests/code_context_test.py, tests/system_test.py
=> fix running mentat from a sub folder and also fix duplicated code features bug

setup.py
I've already pushed this version to PyPI
=> Bump version to 0.1.19

mentat/session_input.py
Fixes #192. I looked into shlex.split and I think it can only ever raise two errors: The unclosed quotation error you found, and a no escaped character error (just type a \ with no characters following it)
=> catch shlex error

mentat/code_context.py, mentat/commands.py, mentat/include_files.py
Fixes #190 and makes warnings more specific.
=> add include and exclude warnings

mentat/parsers/block_parser.py, mentat/parsers/git_parser.py, mentat/parsers/parser.py, mentat/parsers/replacement_parser.py, scripts/translate_transcript.py, testbed/format_examples/block.txt, testbed/format_examples/git_diff.txt, testbed/format_examples/replacement.txt, tests/code_context_test.py, tests/parser_tests/translate_scripts_test.py
A parser for the git diff format is introduced. And a test for the translation script between block, replacement and git_diff formats is introduced.
=> Git diff parsing

.github/workflows/lint_and_test.yml, tests/code_context_test.py, tests/conftest.py
=> fix codecontext test to not be brittle

mentat/code_context.py, mentat/code_edit_feedback.py, mentat/code_file.py, mentat/code_file_manager.py, mentat/commands.py, mentat/conversation.py, mentat/diff_context.py, mentat/llm_api.py, mentat/logging_config.py, mentat/session.py, mentat/session_input.py, mentat/session_stream.py, tests/benchmarks/context_benchmark.py, tests/benchmarks/exercise_runners/clojure_exercise_runner.py, tests/benchmarks/exercise_runners/exercise_runner_factory.py, tests/benchmarks/exercise_runners/javascript_exercise_runner.py, tests/benchmarks/exercise_runners/python_exercise_runner.py, tests/benchmarks/exercism_practice.py
Addresses #202. 
As far as auto-formatting, I used [absolutify](https://github.com/MarcoGorelli/absolufy-imports) locally and it worked great. This PR is the output of that, followed by isort. However it's not maintained, and it doesn't have a 'check' option for our gh-action.
=> standardize import format to absolute

mentat/code_context.py, mentat/code_feature.py, mentat/code_file_manager.py, mentat/code_map.py, mentat/commands.py, mentat/diff_context.py, mentat/interval.py, tests/code_context_test.py, tests/code_feature_test.py, tests/commands_test.py
- Use `ctags` to split files into smaller chunks
- Return chunks rather than full files for search
- Handful of misc related fixes
In the next PR, I'll apply this to generating auto-features in `get_code_message`.
=> Function-level Features

mentat/code_edit_feedback.py
=> Fix Interactive Mode suggestion count

pyproject.toml
This matches what we have in GH actions
=> Add `preview` setting to black in `pyproject.toml`

.github/workflows/lint_and_test.yml
Github actions are free since it's a public repo, this will help people catch things faster as @granawkins suggested
=> Run github actions on all pushes / PRs

mentat/code_feature.py, mentat/config.py, mentat/conversation.py, mentat/session.py, mentat/session_context.py, tests/config_test.py, tests/conftest.py, tests/parser_tests/block_format_error_test.py, tests/parser_tests/block_format_test.py, tests/parser_tests/replacement_format_error_test.py, tests/parser_tests/replacement_format_test.py, tests/parser_tests/split_diff_format_error_test.py, tests/parser_tests/split_diff_format_test.py, tests/parser_tests/unified_diff_format_error_test.py, tests/parser_tests/unified_diff_format_test.py
Part of splitting up this PR: https://github.com/AbanteAI/mentat/pull/225
=> Parser held by config

mentat/config.py, mentat/conversation.py, tests/conversation_test.py
Based on https://github.com/AbanteAI/mentat/pull/244
=> Parser prompt optional

mentat/interval.py
My primary motivation was to get a nice to string for free. Saves us implementing the constructor as a bonus.
=> Interval uses attr

mentat/session.py, mentat/terminal/client.py, tests/system_test.py
Currently if mentat encounters an uncaught exception it hangs and displays nothing. This change makes it print the stack trace and exit.
=> Display exception

mentat/commands.py, mentat/logging_config.py, mentat/resources/conversation_viewer.html, mentat/utils.py
Clicking right and left goes through the history of logs.
=> Conversation command shows old transcripts

tests/benchmarks/exercism_practice.py
We used their prompts in our exercism benchmark and it seems polite to attribute it.
=> Aider attribution

.github/workflows/lint_and_test.yml, mentat/llm_api.py, mentat/session.py, setup.py, tests/conftest.py
Fixes #260.
Working on adding tests for this.
=> change back to find packages

tests/benchmarks/exercise_runners/javascript_exercise_runner.py
The tests for javascript exercism are skipped except for the first one. This change unskips them.
=> Javascript Exercism Fix

setup.py
I've already put this version bump on PyPI
=> version -> 0.1.20

setup.py
=> Release 0.1.21

mentat/__init__.py, mentat/llm_api.py, mentat/sentry.py, mentat/session.py, mentat/utils.py, requirements.txt, setup.py
Adds sentry and a version checking message.
TODO before merge:
Don't track tests
Only track if installed from pip? (Will prevent dev exceptions from sending and any exceptions from modified source)
=> add sentry and version checking message

mentat/__init__.py
=> Release 1.0.2

mentat/sentry.py
=> add version to sentry tag

mentat/resources/templates/conversation_viewer.css, mentat/resources/templates/conversation_viewer.jinja, mentat/resources/templates/conversation_viewer.js
I added a download link to the conversation viewer to make it easier for us to share transcripts. It looks like a bigger change than it is because I wanted to put the script in the head so I had to wrap it in a wait for the DOM to load.
=> Download link added to conversation viewer

mentat/git_handler.py
Accidentally left some redundant code in a previous feature branch that was merged into main
=> Fix merge errors in `git_handler.py`

mentat/conversation.py, mentat/embeddings.py, mentat/llm_api_handler.py, tests/llm_api_handler_test.py
There was actually only one problem (I counted the response tokens as a full message when I shouldn't have), but I also changed a few comments and a function name to make it clearer how counting tokens works.
=> fix token counts

mentat/commands.py, mentat/config.py, mentat/conversation.py, mentat/feature_filters/llm_feature_filter.py
Adds the run command. Will stream both stdout and stderr, and then send it to the model.
=> add run command

mentat/diff_context.py, mentat/session.py, mentat/terminal/prompt_completer.py
=> remove error from invalid treeish and disable diff

mentat/llm_api_handler.py
Fixes the token bug that would cause smaller models (like gpt-3.5.turbo) to return an error as well as fixing the response format bug with gpt-4-vision-preview.
=> fix gpt-4-vision-preview

mentat/llm_api_handler.py
Importantly vision model added. Less importantly legacy models have their context size explicitly given.
=> Model sizes included in dict

mentat/streaming_printer.py, mentat/terminal/client.py
=> prompt toolkit enable suspend

mentat/resources/templates/conversation_viewer.jinja
I was running into trouble when viewing mentat transcripts that were editing html.
=> Messages in conversation viewer are escaped

mentat/llm_api_handler.py
Let me know if you think the `api_guard` decorator is a good idea or not. Also if there's a better name!
Fixes #178
=> Fix crash if there's no internet

mentat/python_client/client.py, mentat/resources/templates/exercism_benchmark.jinja, mentat/session.py, tests/benchmarks/benchmark_result.py, tests/benchmarks/exercism_practice.py
Miscellaneous Changes
* `session_context` added to `session` and used to access transcripts and costs.
* cost added to benchmark dashboard.
Todo:
=> BenchmarkResult class introduced

mentat/auto_completer.py, mentat/command/command.py, mentat/command/commands/agent.py, mentat/command/commands/clear.py, mentat/command/commands/commit.py, mentat/command/commands/config.py, mentat/command/commands/context.py, mentat/command/commands/exclude.py, mentat/command/commands/help.py, mentat/command/commands/include.py, mentat/command/commands/redo.py, mentat/command/commands/run.py, mentat/command/commands/screenshot.py, mentat/command/commands/search.py, mentat/command/commands/talk.py, mentat/command/commands/undo.py, mentat/command/commands/undoall.py, mentat/command/commands/viewer.py, mentat/config.py, mentat/llm_api_handler.py, mentat/session.py, mentat/session_context.py, mentat/session_input.py, mentat/terminal/client.py, mentat/terminal/prompt_completer.py, tests/conftest.py
=> Add command completions and move completions to the server

mentat/resources/templates/css/transcript.css, mentat/resources/templates/js/transcript.js, mentat/resources/templates/transcript.jinja
If you click the button and enter optional feedback your transcript is backed up to an s3 button and we are notified on slack via a lambda.
There's definitely a lot to improve:
* The UX of the dialog.
* There should be a `/feedback` command.
* The lambda should probably be in version control in this repo and deployed via github action.
* The s3 bucket should sit behind a url like transcripts.mentat.ai
* As our jinja templates get more complicated we should eventually introduce some automated linting/testing for them.
But I'd rather not spend too much time polishing. I think we'll get a lot of value from this as it is.
=> Feedback button added

mentat/code_feature.py, mentat/command/commands/search.py, mentat/include_files.py
Allows including with /search. Let me know what everyone thinks about the messages; they feel a bit long and clunky to me, but not sure how to shorten them.
=> add include option to /search command

README.md, mentat/llm_api_handler.py
=> Fix for #408 (explicitly use AsyncAzureOpenAI when required)

.github/workflows/benchmarks.yml, scripts/run_and_upload_benchmarks.sh, tests/benchmarks/benchmark_result.py, tests/benchmarks/benchmark_result_summary.py, tests/benchmarks/benchmark_runner.py, tests/benchmarks/benchmarks/mentat/clojure_exercism_runner.py, tests/benchmarks/exercism_practice.py
* Run in the morning
* JSON copy of data saved to bucket
* Summary string put in slack message
* All benchmarks are run
=> Benchmark cron improvements

mentat/code_context.py, mentat/code_feature.py, mentat/command/commands/clear.py, mentat/config.py, mentat/conversation.py, mentat/diff_context.py, mentat/feature_filters/default_filter.py, mentat/feature_filters/llm_feature_filter.py, mentat/interval.py, mentat/llm_api_handler.py, mentat/session.py, tests/benchmarks/benchmarks/mentat/clojure_exercism_runner.py, tests/benchmarks/benchmarks/mentat/pre_tags.py, tests/benchmarks/context_benchmark.py, tests/code_context_test.py, tests/code_feature_test.py, tests/config_test.py
Add's persistent context. Dependent on #401
=> Persistent context

mentat/embeddings.py, mentat/sampler/sampler.py, scripts/evaluate_samples.py, tests/benchmarks/benchmarks/mentat/license_update.py
Required to run the benchmark_runner successfully
=> Small fixes: embeddings and auto-context

mentat/auto_completer.py
=> Fix autocomplete crash bug

mentat/resources/templates/benchmark.jinja, mentat/resources/templates/conversation_viewer.jinja, mentat/resources/templates/css/transcript.css, mentat/resources/templates/js/transcript.js, mentat/resources/templates/transcript.jinja
There is now a feedback button, share button and download button. Each with helpful tooltips. The feedback button no longer copies the s3 link to your clipboard. They have a consistent style in the upper right.
=> Viewer share upgrades

.readthedocs.yaml, dev-requirements.txt, docs/requirements.txt
=> Read the doc config

tests/benchmarks/benchmark_runner.py, tests/benchmarks/benchmarks/mentat/sample_15223222005645d08b81f093e51d52fe.json
If you put a sample in the tests/benchmarks/benchmarks directory it will be picked up and evaluated by the benchmark runner. Test with:
```
pytest tests/benchmarks/benchmark_runner.py --benchmark -s --benchmarks \
Dummy clojure
```
Based off PR #454 to make use of setup_repo. There's some duplication of sample evaluation.
=> Samples can be run by the benchmark runner

mentat/__init__.py
=> Release 1.0.8

docs/source/user/commands.rst, mentat/command/commands/redo.py, mentat/command/commands/screenshot.py
=> Commands documented

dev-requirements.txt, requirements.txt
=> update git-python to latest version

setup.py
Intended to fix this failure: https://github.com/AbanteAI/mentat/actions/runs/7503169182/job/20427366395
=> Submodules of benchmark picked up

mentat/code_context.py, mentat/conversation.py, mentat/llm_api_handler.py
=> fix returntouser being thrown outside try except bug

tests/license_check.py
=> Remove unneeded licenses

mentat/command/commands/search.py, mentat/feature_filters/llm_feature_filter.py, mentat/parsers/file_edit.py, mentat/parsers/json_parser.py, mentat/terminal/themes.py
The style for warning is changed to yellow in light mode.
=> Color replaced with style in stream

mentat/config.py, mentat/sampler/sampler.py, mentat/session.py, tests/sampler_test.py
=> config.sampler to turn on/off sampler

docs/source/conf.py, mentat/__init__.py
=> Release 1.0.9

benchmarks/benchmark_result.py, mentat/resources/templates/benchmark.jinja
=> Small fixes to run benchmark samples

mentat/config.py, mentat/llm_api_handler.py
Still need to update llm_handler. Let's run the benchmarks before we actually merge.
=> Update openai models

tests/measure_api_speed.py
=> Update measure_api_speed script for new OpenAI api

mentat/llm_api_handler.py
=> add new gpt-3.5-0125 model

dev-requirements.txt
=> Add plotly to dev-reqs for benchmark dashboard

CHANGELOG.rst, docs/source/changelog.rst, docs/source/index.rst, mentat/session.py, mentat/splash_messages.py, mentat/utils.py, tests/splash_messages.py
I added CHANGELOG.rst to our project root and made it a page on the docs. If the user is using an outdated version the most recent changelog is displayed as part of the prompt to upgrade.
=> Changelog added to docs and displayed

mentat/config.py
=> Change default theme

mentat/splash_messages.py
=> Changelog displayed on upgrade

mentat/feature_filters/embedding_similarity_filter.py, mentat/llm_api_handler.py
In my benchmarking it reduces startup time by 0.4s.
=> Lazy load chroma

mentat/conversation.py, mentat/session.py, mentat/splash_messages.py, tests/splash_messages.py
=> Move model check to splash message

.github/workflows/lint_and_test.yml
=> Add timeouts to github actions

mentat/embeddings.py, mentat/feature_filters/llm_feature_filter.py
=> fix-embeddings-loading
