AbanteAI/mentat

- .github/workflows/lint_and_test.yml
- mentat/app.py
Mentat currently supports using Ctrl-C or 'q' to end a session:
However, these ol' fingers are long habituated to using Ctrl-D to end interactive sessions. This PR adds support for `EOFError` to end a session.
> Support ending sessions with Ctrl-D

- mentat/code_file_manager.py
code_file_manager _read_file() expects to receive an absolute path but was accidentally being handed a relative path immediately after the absolute path was computed. 
This caused mentat to be unable to apply changes to files if mentat was launched with a path other than "."
> Fix rel_path vs abs_path typo

- mentat/code_file_manager.py
- tests/code_file_manager_test.py
Fix the bug with too many files in large directories. This bug was caused because we traversed the entire file path tree without ignoring .gitignore files. Now we do those together.
> Fix bug filter gitignore sooner

- README.md
- mentat/app.py
- setup.py
Tested with pyenv, pip won't let you install packages if your python version is too low. There is no point in making a version check in mentat since it won't even run below 3.10 because of the match statements.
> make required python version 3.10 or higher

- mentat/conversation.py
- mentat/llm_api.py
- tests/code_file_manager_test.py
- tests/config_test.py
- tests/conftest.py
- Move checking model availability from `Conversation.__init__` to new function in llm_api. Also it now checks for `gpt-4-0314` on startup and exits gracefully if it isn't available. This function is also mocked, which fixes a bug where tests would fail due to an attempted OpenAI call to get the model list when users had a config with `allow_32k=True`. 
- Clarify the check being made in `test_path_gitignoring`, and change assert to test paths are the same.
- Move `monkeypatch.chdir` fixture into `temp_testbed` to improve clarity.
> Fix test bugs; Clean up tests

- docs/configuration.md
- mentat/code_file_manager.py
- mentat/config_manager.py
- mentat/default_config.json
- setup.py
- tests/code_file_manager_test.py
Summary:
Adds several optional configuration properties to improve handling of large projects to work around limits in the number of tokens that can be handled by GPT-4 and limits in the number of files that can be passed to the git `repo.ignored()` function.
From the modified `docs/configuration.md`:
Optional lists of regex patterns that determine which files or directories will be included 
or excluded from context. Either or both lists can be provided. If the file path matches 
both an inclusion rule and an exclusion rule, the exclusion rule always wins (including 
for example filetype exclusion wins over filepath inclusion).
```
{
"filepath-include-only-these-regex-patterns": [".*/include_this"],
"filepath-exclude-these-regex-patterns": [".*/exclude_this"]
}
```
There is currently an …
> Improve handling of large projects

- README.md
- docs/configuration.md
- mentat/app.py
- mentat/code_file_manager.py
- mentat/config_manager.py
- mentat/default_config.json
- tests/code_file_manager_test.py
Remove filetype checking, add glob includes, and fix a few bugs. To test include globs in zsh, put quotes around paths.
In case you're wondering why the glob path expansion is at the very beginning (outside of codefilemanager), there are 2 reasons:
1. We need it to resolve the git root
2. Because some terminals (such as zsh) automatically expand glob patterns, I think it's best to do it at the very beginning so there is no difference between terminals.
> Remove filetype checking

- README.md
The --exclude flag needs to be preceded by a directory path. Without a directory path the mentat command returns a no context provided error.
> Fix typo in readme for --exclude

- mentat/app.py
- mentat/code_change.py
- mentat/logging_config.py
- mentat/model_error.py
- mentat/parsing.py
- tests/model_error_test.py
Adds error handling for if the model messes up; if it's a non-fatal error, will keep accepting the models changes, otherwise it will stop and only use the existing changes.
I think the error code for codechange feels very clunky and messy; for the non fatal errors we can't throw an exception though, and this was the best I thought of. Let me know if you have any ideas to make it cleaner.
> Model error handling

- mentat/app.py
- mentat/code_change.py
- mentat/code_file_manager.py
- mentat/errors.py
- mentat/git_handler.py
- mentat/llm_api.py
- mentat/parsing.py
- mentat/user_input_manager.py
- tests/code_file_manager_test.py
- tests/git_handler_test.py
Don't raise KeyboardInterrupts. Also raise exceptions instead of exit() so we can print the final cost.
> Use custom exceptions instead of KeyboardInterrupts and exit()

- mentat/llm_api.py
- mentat/parsing.py
Give user a different response for a missing API key and an invalid one. 
Fixed a spot where we weren't raising an error (a null statement)  which led to a bug with the cost reporting.
Also just give the OpenAI error message as it can be more specific than we can.
> Fix openAI error messages and API key messages

- mentat/git_handler.py
Currently, mentat won't work with a msys2-installed Git on Windows because when executing `git rev-parse --show-toplevel`, it will produce a non-compatible path (e.g. /c/Users/xxx/mentat).
According to [Msys2](https://www.msys2.org/docs/git/), they suggest to use `git rev-parse --show-prefix`, which outputs a relative path from the root to the current working directory and it is both a valid Unix and Windows path.
So I modified the related code, and it works fine for my setup.
> Fix git root parsing when using msys2 git on Windows

- README.md
- mentat/app.py
- mentat/code_map.py
- mentat/conversation.py
- mentat/prompts.py
- testbed/scripts/echo.py
- tests/benchmark_test.py
This PR adds a high-level code map generated from [ctags](https://github.com/universal-ctags/ctags) into the system prompt which gives the model more context on what other code/classes/methods/etc. it can use that haven't been directly added into the model context by the user. 
This implementation takes inspiration from how [Aider](https://github.com/paul-gauthier/aider) works with large codebases. [Here's a writeup](https://aider.chat/docs/ctags.html) from the author of Aider on how it works.
This work is a prerequisite for having Mentat automatically add new source code from files outside the context.
Need to finish these before this PR is ready for review:
> Add high-level code map to system prompt

- mentat/app.py
- mentat/code_file.py
- mentat/code_file_manager.py
- tests/code_file_manager_test.py
The user can specify a partial file with : syntax e.g. test.txt:1-2,5 will put only lines 1,2 and 5 in scope. It is checked if that file with a colon already exists. For this a File object is created in the code_file_manager which has the path and segment information bundled.
The expand function is moved from app.py to code_file_manager.py
Test with:
```
mentat README.md:6-12,16
> Replace all instance of the word mentat with test.
```
> Partial files allowed

- mentat/mentat_prompt_session.py
Instead of exiting immediately on ctrl-c, we clear any text that's been typed. This is pretty common behavior for other cli tools, so I added this since I keep accidentally quitting mentat sessions after trying to clear a bunch of text I just typed.
> Clear prompt with ctrl-c before quitting

- mentat/app.py
This line was intended to support args like `mentat/git_handler.py:1-12,20-21`, but if the user passes an invalid file that doesn't contain a ':', it crashed instead of returning a useful message.
> fail gracefully for paths without interval data

- README.md
- setup.py
- tests/license_check.py
Thanks to the very helpful previous owner of "mentat" on PyPI, I now have control of it and we don't need to use "mentat-ai" on PyPI anymore. Should help reduce confusion!
The original package did had releases with version numbers `1.0.0` and `1.0.1`, I have "yanked" those releases (and we'll have to skip those). There is also the option to delete them. These are old and I'm sure no one depends on them so maybe that's best.
> Switch package name on PyPI

- mentat/app.py
- mentat/code_context.py
- mentat/code_file_manager.py
- mentat/code_map.py
- mentat/conversation.py
- tests/code_file_manager_test.py
This is a small PR building on #86 which moves the CodeMap and DiffContext from `code_file_manager` to `code_context`. 
The next steps (in separate PRs) will be
- Refactor CodeFile to handle read/write ops
- Streamline the context-generating process inside CodeContext
- Add Embeddings
> Refactor context

- mentat/llm_api.py
- mentat/logging_config.py
- tests/benchmarks/exercism_practice_python.py
Removes logs from test environment, but not from benchmarks. We could also put benchmark logs in a subdirectory "benchmark_logs" instead of having them all in one directory; what do you think?
> remove logging from test environment

- tests/benchmarks/README.md
- tests/benchmarks/exercism_practice.py
- tests/conftest.py
I also changed the printing so results are automatically added to results.txt and summary information is added to the tqdm description.
This is sort of a mess since there's a lot of subtle differences between how the javascript tests and python tests are run. If we end up wanting to support more languages we might want to have an abstract exercism_benchmark class with language specific inheritors that implement the methods that run the tests, check if the tests ran and setup the repo.
> Exercism Benchmark supports javascript

- mentat/code_context.py
- mentat/code_edit_feedback.py
- mentat/code_file_manager.py
- mentat/code_map.py
- mentat/commands.py
- mentat/config_manager.py
- mentat/conversation.py
- mentat/diff_context.py
- mentat/git_handler.py
- mentat/llm_api.py
- mentat/parsers/block_parser.py
- mentat/parsers/file_edit.py
- mentat/parsers/parser.py
- mentat/parsers/replacement_parser.py
- mentat/parsers/split_diff_parser.py
- mentat/session.py
- mentat/terminal/client.py
- mentat/terminal/prompt_completer.py
- mentat/terminal/prompt_session.py
- tests/code_context_test.py
- tests/code_file_manager_test.py
- tests/commands_test.py
- tests/config_test.py
- tests/conftest.py
- tests/diff_context_test.py
Moves git root out of config and turns all of the singletons into contextvars, instead of passing them around everywhere. 
Couple of notes:
I removed the 'self.config', 'self.code_file_manager', etc. references everywhere except for the Session still having self.stream; we can change that in the future if we need to, but with the upcoming RFC server change, I decided to wait until we know what it's all going to look like.
Do you think we should have CodeFileManager, CodeContext, and Conversation be regular instances? We might want to have multiple of them in the future. On the other hand, I think it makes a lot more sense in our current codebase for them to be singletons. Let me know what y'all think!
> turn all singletons into context vars, remove git_root from config

- mentat/python_client/client.py
- tests/benchmarks/exercism_practice.py
- tests/clients/python_client_test.py
A light client for mentat is created and used in the exercism test. I think we'll mostly find value in this for testing but I could imagine people wanting to interact with mentat programmatically. For instance maybe you want to give GPT-4 access to mentat.
> Python client added

- mentat/terminal/client.py
- tests/clients/terminal_client_test.py
- tests/conftest.py
Windows doesn't have signals the same way *nix systems do, so asyncio's loop.add_signal_handler isn't implemented in Windows. The main difference between signal.signal and add_signal_handler is that add_signal_handler is asyncio safe, while signal.signal isn't; when the SIG_INT gets caught by signal.signal now, we could be in the middle of an async coroutine and it would be interrupted. I don't think this causes any race conditions; all we do is send an interrupt signal through the sessionstream, but I would like if @waydegg looked over this and gave his thoughts before merging.
Additionally, the reason this wasn't caught by testing is because we weren't running any TerminalClient tests on Windows (due to an issue I discovered a while ago involving PromptToolkit and Github Actions Windows …
> use signal.signal instead of loop.add_signal_handler

- mentat/conversation.py
- setup.py
Our requirements cannot be read properly by brew because we read it with a relative path in setup.py. I made a few other small changes in setup.py which caused me to notice an import error in conversation.py so I fixed that too.
> Version bump to 0.1.16

- MANIFEST.in
- setup.py
The `requirements.txt` was not being found by brew because it was not included, not because it was specified with relative path. Data files are now specified via Manifest and the `requirements.txt` is added. You can test that the `requirements.txt` and other files are included with the following command:
```
python setup.py sdist bdist_wheel
```
> Manifest added

- mentat/code_edit_feedback.py
- mentat/commands.py
- mentat/conversation.py
- mentat/resources/conversation_viewer.html
- mentat/utils.py
- scripts/transcript_viewer.py
TODO:
Increase aesthetic appeal
Should we make conversation command hidden? It probably isn't too useful to the average viewer, and it looks very hacked together
> Conversation viewer

- mentat/code_context.py
- mentat/terminal/client.py
- changes default auto-token limit to 0 (instead of model max)
- doesn't print "CodeMaps: Enabled/Disabled" if the auto-token limit is 0 (since they won't be included either way)
Before making a non-zero default again we need to make it clearer to users what costs will be and make sure the extra context helps enough
> Default to auto-token limit of 0

- mentat/parsers/block_parser.py
- mentat/parsers/replacement_parser.py
- tests/parser_tests/block_format_test.py
- tests/parser_tests/inverse.py
- tests/parser_tests/replacement_format_test.py
Inverse test refactors to prevent duplication. File edits are compared instead of llm messages.
Sorry I keep saying "X isn't worth doing right now" and the immediately doing it in the next PR. `attr` and `python` made is easier to compare the equality of the `FileEdit`s than I realized. Strictly speaking we're still testing more than we care about because the test woudl fail if the inverse changed the order of the `FileEdit`s. We could sort or add to a set before comparing but it seems hacky to have attr implement an order or hash method just for this test.
> Replacement parser inverse

- mentat/parsers/diff_utils.py
- mentat/parsers/unified_diff_parser.py
- mentat/resources/prompts/unified_diff_parser_prompt.txt
- tests/parser_tests/unified_diff_format_error_test.py
- tests/parser_tests/unified_diff_format_test.py
Fix unified diff bugs; tweak prompt a bit to be slightly more similar to the git diff format. Things I still haven't tried yet:
Adding a/ and b/ to filenames (like a git diff would have)
Having diff --git file_name_1 file_name_2 line at start
Working on seeing if adding those has any significant effect (although I doubt it will)
> Unified diff tweaking

- mentat/parsers/file_edit.py
- mentat/session_input.py
- tests/parser_tests/block_format_error_test.py
- tests/parser_tests/block_format_test.py
- tests/parser_tests/replacement_format_error_test.py
- tests/parser_tests/replacement_format_test.py
- tests/parser_tests/split_diff_format_test.py
- tests/parser_tests/unified_diff_format_test.py
Fixes #173. I'm going to work on adding SessionContext after this, since it clearly would help with circular imports quite a bit
> fix context checking in fileedit, remove test.conftest imports

- mentat/parsers/block_parser.py
- mentat/parsers/replacement_parser.py
- mentat/parsers/split_diff_parser.py
- mentat/parsers/unified_diff_parser.py
- tests/parser_tests/inverse.py
Fixes #181. I meant for this to be the default when I designed the FileEdit and Parser classes, but clearly I forgot about it along the way.
> switch to use abs-paths for parsers renames

- mentat/broadcast.py
- mentat/conversation.py
- mentat/llm_api.py
- mentat/parsers/file_edit.py
- mentat/python_client/client.py
- mentat/session.py
- mentat/session_stream.py
- requirements.txt
- tests/benchmarks/exercism_practice.py
- tests/clients/python_client_test.py
Add backoff to llm api calls and stop errors from bricking benchmarks. @jakethekoenig I don't really like the way I had to set up the python client to detect when the session is stopped, but because of the way we run the benchmarks (where we wait for the next input request to confirm that all changes have been made) I'm not sure of a better way to do it. Maybe in the future we should have the server send a message confirming that changes have been written? This could be useful for the vscode extension too.
> Backoff llm api calls

- mentat/terminal/prompt_completer.py
Fixes #191. We still suggest paths relative to the git root (rather than just the file_name) because that path is what the model sees and outputs and will most likely be the best one to use in the prompt.
> fix abs path auto completions

- mentat/code_file_manager.py
- tests/code_file_manager_test.py
Fixes #188. Since we don't add files that don't exist to context, we need to create the file before we include it.
> Create file not in context

- mentat/diff_context.py
- tests/diff_context_test.py
This addresses an issue in the latest comment in #154. We recently switched from relative to absolute paths in several places, and diff_context was overlooked.
> update diff_context and tests to use absolute path

- scripts/git_log_to_transcripts.py
A script that:
* Iterates over github commits
* Uses GPT to make a request and step by step summary
* Converts the diff to a replacement format llm response
* packages them into training examples
Usage:
```
./scripts/git_log_to_transcript.py
```
will iterate over the last 10 commits in mentat and convert them. There are flags to choose the repo, the start commit, and the number of commits.
This is very close to being able to generate code context benchmarks similar to @granawkins's. I plan to do that in a followup PR.
> Generate synthetic transcripts from commits

- mentat/code_feature.py
- mentat/code_map.py
- tests/benchmarks/context_benchmark.py
- tests/code_feature_test.py
- tests/code_map_test.py
- tests/conftest.py
This PR removes the need for CodeMap to be run on a file inside of a git repository. 
This is part of a larger effort to allow Mentat Sessions to be started in a non-git directory, which is required by the VSCode extension executable along with just being a very nice feature to have (users can open Mentat anywhere on the filesystem).
> Remove git dependency for CodeMap

- mentat/config.py
After @jakethekoenig refactored the config, default tokens was accidentally turned into None instead of 0; this turns the default back to 0.
> reset auto tokens default to 0

- mentat/parsers/git_parser.py
- testbed/format_examples/block.txt
- testbed/format_examples/git_diff.txt
- testbed/format_examples/replacement.txt
When a git diff shows exactly one line changed the number which says how many lines were changed is omitted. This is rarer than it sounds because git usually gives context around a change. But it happens for one line files like .nvmrcs.
> Git Parser Fix

- scripts/git_log_to_transcripts.py
- scripts/select_git_transcripts.py
- tests/benchmarks/utils.py
* We ask GPT to respond in json and give a little more information about the commit.
* The mocked transcript is stored in the same cache.
* A new script is made to make the jsonls which selects transcripts with specified properties from the commit_information.json
* `git show --first-parent` is used so we can get a git diff for pull requests (thanks gpt)
* The repo name is inferred from the url instead of being constant.
* We checkout main instead of head.
> Git transcript processing tweaks

- .github/workflows/lint_and_test.yml
In https://github.com/AbanteAI/mentat/pull/222 I enabled github actions checks to run on pushes to all branches, but then to reduce "duplicate" checks on PRs I disabled PR checks unless they came from another fork.
But these aren't actually duplicate checks - the "push" checks run on the commit, the "pull request" checks run on the merged code! So we definitely want the "pull request" to run!
The downside is just that we see twice as many checks at the bottom of each PR
> Don't skip Github Action PR checks

- tests/benchmarks/edit_rubric_benchmark.py
- tests/benchmarks/exercism_practice.py
- tests/conftest.py
[benchmark_results.json](https://github.com/AbanteAI/mentat/files/13221332/benchmark_results.json)
[benchmarks.json](https://github.com/AbanteAI/mentat/files/13221333/benchmarks.json)
Mentat is given a repo, commit and prompt and attempts to make edits. gpt-4 grades. The actual edits can also be graded. You can generate benchmarks with `./scripts/git_log_to_transcripts.py`. You can also use the attached `benchmarks.json`. If you copy it to `tests/benchmarks/repos/mentat` (where you should clone mentat). I'd like to keep this PR small but in the future we should have:
* An html results page like for exercism
* Comparative quality benchmarks where we put both the actual and generated diffs in context. Both a version where we tell gpt which is real and one where we don't.
My first impression …
> Rubric benchmark

- mentat/config.py
- tests/config_test.py
The boolean flags would still be set to true or false if no flag was added so settings set in the config file would be overwritten with no flag. Namespace values are now not stored if they are equal to the default.
Also I realized attrs provided a boolean converter so I removed mine.
> Fix: cli flag parsing

- mentat/code_context.py
- mentat/session.py
- tests/diff_context_test.py
Addresses #239: Use --diff or --pr-diff to set paths if no paths arg given. We used to do this but it must've gotten lost at some point.
Another issue: If the diff/pr-diff is too big for context, it raises a MentatError but doesn't close Mentat. Seems to be a lifecycle issue - the shutdown listeners maybe not yet in place. I'd defer to @waydegg on the best way to address this. Might be related to #237 too - handling errors in the session startup phase.
> Include paths from diff/pr-diff if no paths given

- mentat/auto_context.py
- mentat/code_context.py
- mentat/code_feature.py
- mentat/code_file_manager.py
- mentat/config.py
- mentat/include_files.py
- mentat/resources/prompts/feature_selection_prompt.txt
- mentat/resources/prompts/feature_selection_prompt_training.txt
- scripts/git_log_to_transcripts.py
- tests/auto_context_test.py
- tests/benchmarks/context_benchmark.py
- tests/benchmarks/utils.py
- tests/code_context_test.py
- tests/code_feature_test.py
- tests/code_file_manager_test.py
Add the ability to use llm for context selection in benchmarks. In future PRs we'll add a command/arg to use this in the actual mentat - this lays the groundwork for that.
- Move auto-context logic from `CodeContext._get_auto_features` to `mentat.auto_context.py`
- Define two algos: _greedy (reproduce current results) and _llm
- Use _llm algo in `get_git_log_transcripts` to build benchmark['expected_features'].
What this branch can do is:
1. Generate benchmarks using @jakethekoenig's script: `./scripts/git_log_to_transcripts.py --repo <gh-link>`
2. Run context_benchmarks against the created benchmarks: `pytest -s tests/benchmarks/context_benchmark.py --benchmarks`. This will print your precision/recall first with the greedy method, then llm.
> Auto context with llm

- mentat/commands.py
- mentat/conversation.py
- mentat/session.py
- tests/commands_test.py
- tests/conftest.py
- tests/conversation_test.py
* A get_messages method is added to conversation that manages whether to include the system prompt.
* While incorporating @PCSwingle 's feedback to make messages private I realized the clear command accessed it directly so I added a clear method for it to use instead.
> Parser change midconversation

- mentat/code_context.py
- mentat/embeddings.py
Two changes:
- Use sqlite database instead of json/gzip. We save ~10s by not writing the gzip file, and lose ~0.3 seconds reading from the database instead of just from memory.
- Make up to n=10 (arbitrarily) simultaneous calls to the embeddings API, handle minute-level RateLimits
A future optimization could be to use [Annoy](https://github.com/spotify/annoy). This would replace that 0.3s call to the database and ~0.1s calculating cosine similarity. 
(all these numbers are from running mentat on the mentat repo)
> Speed up embeddings/search

- mentat/code_context.py
- mentat/code_map.py
- mentat/config.py
- mentat/embeddings.py
- mentat/feature_filters/default_filter.py
- tests/benchmarks/context_benchmark.py
- tests/benchmarks/exercism_practice.py
- tests/code_context_test.py
- tests/code_file_manager_test.py
- tests/config_test.py
This PR consolidates a lot of args and settings related to context.
Removed:
- use_embeddings (always on)
- no_code_map (always try to use)
- auto_tokens (config.maximum_context achieves the same thing)
Added:
- auto_context: bool = False (use cmaps, embeddings and llm to generate the best possible context)
I leave `CodeContext.use_llm` and set it to True by default. This is currently used by tests so that we can test filter behavior without calling the LLM.
> Auto context interface

- mentat/config.py
In benchmarks smaller temperature settings were always associated with improvements in performance. This is the smallest value I tested.
> Default temperature changed to 0.05

- mentat/git_handler.py
Silence all subprocess STDERR output from git subprocess calls. If there is an error, an exception will be thrown. We don't rely on STDERR for anything, and atm the Terminal Client gets a bunch of console output for git errors even though we already handle that w/ Exception try-catch blocks.
*This PR is part of a series of PRs to remove `git_root` from Mentat, and allow Sessions to be run anywhere on the filesystem.*
> Fix Git subprocess calls to suppress error output

- mentat/code_feature.py
- mentat/code_map.py
- mentat/config.py
@granawkins I added a new CTAG type; you were previously checking for if line number or name was None; in my own testing I couldn't find anywhere where it would've been None, but I don't have much experience with ctags. Do you know if it can ever be None?
> fix errors in vscode pyright linter

- mentat/config.py
- mentat/conversation.py
- mentat/llm_api.py
- mentat/session.py
- tests/commands_test.py
Rather than add a model 'waterfall', I decided to leave control in the user's hands and just give a warning that they should use /config model <model_name>. I also set gpt-4 turbo as the default model.
> gpt-4-turbo default, rate limit message

- mentat/code_context.py
- mentat/config.py
Short PR to add the `auto-tokens` arg back, with a default of 4000, which applies only to additional files added by `auto-context`, as discussed.
This is quite necessary now that `gpt-4-1103` is the default model, so I'm doing a tiny PR to fast-track it.
> add auto-tokens argument back

- mentat/session.py
- mentat/vision/vision_manager.py
Currently an exception is thrown if the user closes the browser and tries to take another screenshot. According to Chat GPT this is the best way to tell if the browser is still open.
The browser is also closed when the session ends.
> Browser reopened if closed

- mentat/code_edit_feedback.py
I found that the model was much better at answering whether or not it's changes were applied (without being given access to the files to see if they were applied) with this wording.
> change no changes applied message

- tests/benchmarks/benchmark_runner.py
- tests/benchmarks/benchmarks/mentat/license_update.py
- tests/conftest.py
This represents a break from how I was thinking about benchmarks previously:
* Rather than generating many benchmarks it'll likely be more valuable to have a few that we can understand well.
* If we're going to write or understand them by hand I'd much prefer to have them in python than json.
- It'll be easy to convert the json tests into this format when we are ready for generated tests.
* Similar to how pytest discovers test files I think our benchmark runner should discover benchmarks in the benchmark directory.
* For simple benchmarks we should have a deterministic test to see if gpt succeeded which is what I've done for this one test.
* When I introduce a more complicated benchmark I'll add GPT grading with a hand made context for the task.
* Part of what makes a task challenging is …
> Benchmark runner and simple benchmark added

- mentat/terminal/prompt_session.py
Currently if a user uses one of our keybindings after entering reverse search with <c-r> they'll have counterintuitive behavior.
> Keybindings disabled while searching

- mentat/code_map.py
Adds attribution comment to the top of `code_map.py`, linked to Aider. The original PR implementing this code (https://github.com/AbanteAI/mentat/pull/66) referenced Aider as inspiration but it should be in the code as well.
Resolves #302
> Add inspiration comment to code_map.py

- tests/diff_context_test.py
For whatever reason (git version?) some of these tests failed when I ran locally as it expected master but had main as the default branch. With this update they work on my machine and still work on Github actions too (hopefully, we'll see)
> Fix tests that failed on my laptop

- mentat/conversation.py
Patch for the Vision update - we should still pass a prompt string to get_code_message.
> pass prompt to get_code_message as a string

- mentat/llm_api_handler.py
- mentat/session.py
- tests/conftest.py
If we're in a benchmark we need to initialize the client. While I was there I fixed a typo.
> Initialize client not mocked in benchmarks

- mentat/code_context.py
Fixes #296. @granawkins the reason this was crashing was because we try to read the file when determining the checksum for the features, and the features aren't changed when the include files are changed. Before merging this, I think we should have the exclude_files function exclude files from features as well; I wanted to ask you though since this is your code.
> dont use non existent files in checksum

- mentat/code_edit_feedback.py
- mentat/code_file_manager.py
- mentat/interval.py
- mentat/llm_api_handler.py
- tests/code_file_manager_test.py
- #316 Calculate and stream `{n_applied}/{n_total} changes applied.` instead.
- #293 Make intervals inclusive-start, exclusive-end.*
\*This changes the interface (you'll see the test) so you need to specify e.g. `myfile.py:1-2` in order to include just line 1. We already do some preprocessing of these command-line args (splitting intervals into different features), so we could add a transformation to keep the cli-arg end-inclusive like they were. Thoughts?
> Auto context issues

- dev-requirements.txt
Not required for development and ipython (an ipdb dependecy) keeps conflicting with our pinned prompt toolkit version.
> Remove ipdb from dev-requirements.txt

- mentat/terminal/prompt_completer.py
When you ran in a subdirectory, completions (for function/class names) didn't pop up. I found this was due to using paths relative to the git root. When the mis-pathed files couldn't be opened we were calling `logging.debug(f"Skipping {file_path}. Reason: file not found")`
Fixes #317
> Bugfix: completions don't work when Mentat run in subdirectory

- mentat/conversation.py
Currently maximum context is determined at conversation initialization. Now it is checked before calling the llm as well. This allows users to change it mid session as well as preventing possible errors in long conversations.
> Maximum context checked

- mentat/resources/templates/conversation_viewer.css
- mentat/resources/templates/conversation_viewer.jinja
Fixed #342. Use \<pre\> tags to display text so whitespace appears normally; this always means we don't need to replace newlines with \<br\> tags.
> add pre tags so whitespace isnt collapsed

- mentat/parsers/parser.py
In #274 we changed file_lines to abs path, but spot was missed, meaning context lines and removed lines couldn't be printed.
> fix removed lines bug

- .github/workflows/benchmarks.yml
- scripts/run_and_upload_benchmarks.sh
A daily github action that:
- Runs one small benchmark (we should expand after we've validated this)
- Uploads the results.html to a public s3 bucket.
- Secrets to upload to the bucket are already added.
- I think it's fine if the benchmarks are public since all the code to run them is public anyway. If we clean them up a bit and make a central dashboard I could even see hosting the bucket as a static site at benchmarks.abante.ai
- Makes a slack message in the benchmarking channel.
- The webhook url is an already added secret. It's not that important to keep this secret but in theory people could spam us with it.
> Github action to run and upload benchmarks

- mentat/__init__.py
should release after recent bug fix: https://github.com/AbanteAI/mentat/commit/255d9ee18e680d1c3ff8bd2ca9e0f77de0dc255f
> Release 1.0.5

- mentat/code_context.py
- mentat/include_files.py
@granawkins @waydegg  is there a reason the included files was duplicated? I assume it was the result of a merge conflict with one of Wayde's big PR's, but not sure and wanted to make sure I didn't miss anything.
> fix display context double and white directory names

- mentat/code_context.py
- mentat/code_feature.py
- mentat/include_files.py
- mentat/interval.py
It's been pointed out that the way we check for intervals `path_str.rsplit(":")` won't work on a Windows absolute path. This fixes that by doing it with `re` in a helper func.
> Add helper func to split interval string from path

- mentat/code_context.py
- mentat/git_handler.py
- mentat/include_files.py
- tests/system_test.py
Fixes #393. Turns out git ls-files returns directories instead of files for any inner git repositories it finds!
> fix inner git repository bug

- mentat/resources/templates/benchmark.jinja
- mentat/resources/templates/css/benchmark.css
- mentat/resources/templates/exercism_benchmark.jinja
- tests/benchmarks/benchmark_result.py
- tests/benchmarks/benchmark_result_summary.py
- tests/benchmarks/benchmark_runner.py
- tests/benchmarks/benchmarks/mentat/license_update.py
- tests/benchmarks/benchmarks/mentat/pre_tags.py
- tests/benchmarks/exercise_runners/abstract_exercise_runner.py
- tests/benchmarks/exercism_practice.py
The BenchmarkResult class and it's viewer are made more general with the following changes:
* Attributes of a benchmark result can be marked aggregateable and if they are the summary will compute and display the appropriate statistic for them: average, percent, sum. The property is not displayed if it is none for all benchmarks. If only a a subset of the benchmarks define it the percent is given in parenthesis next to the aggregated number.
* Attributes of a benchmark can specify how they should be displayed: text, code, transcript or json.
Now if you introduce a new benchmark with a new property you can add the property to the BenchmarkResults class along with the appropriate metadata. This won't break previous benchmarks and if appropriate it is easy to set it for them.
misc:
* …
> Benchmark Runner results shown in viewer

- dev-requirements.txt
- docs/Makefile
- docs/make.bat
- docs/source/conf.py
- docs/source/index.rst
- docs/source/mentat.command.commands.rst
- docs/source/mentat.command.rst
- docs/source/mentat.feature_filters.rst
- docs/source/mentat.parsers.rst
- docs/source/mentat.prompts.rst
- docs/source/mentat.python_client.rst
- docs/source/mentat.rst
- docs/source/mentat.terminal.rst
- docs/source/mentat.vision.rst
- docs/source/modules.rst
- mentat/session_input.py
- requirements.txt
Add the basic Sphinx setup to create documentation for the mentat module. This is done by
- Creating the docs/source directory, adding in the mininmal required sphinx code (using sphinx-quickstart and sphinx-apidocs).
- Change the theme to sphinx_rtd_theme.
To generate the documents change to the docs folder and run the commane
`make clean html`
The resulting dpcumentation will be in the docs/build directory and can be viewed using your browser e.g. `firefox docs/build/html/index.html`
> Add initial basic Sphinx documentation 

- mentat/code_file_manager.py
- mentat/parsers/block_parser.py
- mentat/parsers/git_parser.py
- mentat/parsers/json_parser.py
- mentat/parsers/parser.py
- mentat/parsers/replacement_parser.py
- mentat/parsers/unified_diff_parser.py
- mentat/python_client/client.py
- mentat/terminal/client.py
- tests/code_file_manager_test.py
The code_file_manager uses absolute paths as keys but paths passed in may not be resolved leading to keyerrors. The cwd passed to sessions are also now resolved.
To be concrete this fixed two bugs:
* If you started mentat with `mentat --cwd mentat` (from outside the mentat dir) you could not make file edits.
* If you added a file outside the cwd such as `mentat ~/.zshrc` (assuming you're not in home) you could not edit it.
> Files outside cwd can be edited

- mentat/parsers/block_parser.py
Because we strip the line before checking if it's special, a new line with nothing but whitespace characters would always be a positive even after the newline character was added. Now, it only matches if it's a new line and there were non whitespace characters in the line as well.
> fix bug not showing empty lines when streaming

- mentat/agent_handler.py
- mentat/code_context.py
- mentat/code_feature.py
- mentat/code_file_manager.py
- mentat/command/commands/search.py
- mentat/conversation.py
- mentat/cost_tracker.py
- mentat/diff_context.py
- mentat/errors.py
- mentat/feature_filters/default_filter.py
- mentat/feature_filters/llm_feature_filter.py
- mentat/feature_filters/truncate_filter.py
- mentat/feature_filters/user_include_sort_filter.py
- mentat/git_handler.py
- mentat/include_files.py
- mentat/interval.py
- mentat/llm_api_handler.py
- mentat/parsers/file_edit.py
- mentat/session.py
- tests/code_context_test.py
- tests/code_feature_test.py
- tests/code_file_manager_test.py
- tests/diff_context_test.py
- tests/feature_filters/llm_feature_filter_test.py
- tests/feature_filters/truncate_filter_test.py
> Cleanup code context and code features

- mentat/conversation.py
- mentat/transcripts.py
- tests/conversation_test.py
Certain openai "compatible" endpoints want the content to be a string and fail if type is specified. This change makes us compatible with llama.cpp and litellm's openai compatible endpoints.
> Fix: user message is string unless image included

- mentat/python_client/client.py
- mentat/session.py
- scripts/evaluate_samples.py
- tests/benchmarks/benchmark_runner.py
- tests/benchmarks/exercism_practice.py
- tests/clients/python_client_test.py
- tests/sampler_test.py
Currently if the session fails the python client will continue to wait for input. This change interrupts the call_mentat function when the session fails and prints out the session's exception.
> Fix: Python client throws exception with session

- mentat/embeddings.py
- tests/embeddings_test.py
The API actually allows 8192 tokes *per input*, and up to 2048 inputs, so we'll hardly ever need to send more than one batch. I opened a new repo and ran `mentat -a`, and saw it added 10MB to the embeddings database in ~3 seconds.
> Update embeddings batching based on new understanding of limits

- mentat/session_input.py
If we have a leading space on the prompt command line - e.g. ">>>      /run ls" the command fails while ">>>/run ls" works.
The reason is that the code looks for a "/" as the first character but the first character is a whitespace. Trimming the whitespace fixes the issue. 
Have only trimmed it on the left in case the commands being run need trailing whitespace  (things like xargs would use them).
> Strip leading spaces when checking for commands

- README.md
- mentat/cost_tracker.py
- mentat/llm_api_handler.py
As described in #429, `chunk.choices` is sometimes an empty array, so we should guard accordingly. This only occurs when streaming responses, so I have left other occurrences of unguarded List indexing `choices[0]` as-is.
The documentation change is not related to this particular issue, but it does pertain to Azure OpenAI in general so I decided to include it in the PR.
> Fixes #429 (ignore chunks with empty choices array)

- mentat/session_input.py
Reverts AbanteAI/mentat#427. @jakethekoenig and I decided that this change doesn't make too much sense; for one, this doesn't seem like intended behavior, and 2 being that autocomplete doesn't work with leading spaces.
> Revert "Strip leading spaces when checking for commands"

- README.md
- mentat/code_context.py
- mentat/conversation.py
- mentat/errors.py
- mentat/feature_filters/default_filter.py
- mentat/llm_api_handler.py
- mentat/session.py
- tests/code_context_test.py
- tests/conftest.py
Replaces #450. After discussing with @jakethekoenig, we feel this is a better alternative than using litellm directly in the codebase.
> Add documentation for using other models, make it easier to use non OpenAI models

- tests/benchmarks/benchmark_runner.py
- tests/benchmarks/benchmarks/mentat/license_update.py
Two small things I noticed, seemed best to give them their own PR.
Messages is currently loaded backwards into a Sample - that's an error I meant to fix in v0.1.1, maybe next week. So for now either add them in reverse or remove altogether.
> small fixes to benchmarks

- README.md
> Readme shorted. Docs referenced

- mentat/session_stream.py
Super basic documentation for the sessionstream's channels and their various kwargs. Hopefully this will make it easier to  ensure full functionality for new clients. @waydegg this may be helpful for the VSCode client to make sure you haven't missed anything.
> add session stream channel documentation

- mentat/resources/templates/js/transcript.js
- scripts/run_and_upload_benchmarks.sh
benchmarks.mentat.ai and transcripts.mentat.ai now point to s3 buckets. This change gives users the pretty URLs for transcripts and benchmarks.
The lambda currently puts transcripts in both buckets so the functionality will continue to work for old versions.
> Benchmark and transcript Urls changed

- scripts/run_and_upload_benchmarks.sh
Fixes a failure in this benchmark run: https://github.com/AbanteAI/mentat/actions/runs/7506292785/job/20437394457
It also complains about `benchmark_repos/exercism-python/results.json: No such file or directory`. I'm not sure exactly what the cause of that is because I see the file there locally.
> Remove no longer used flags

- benchmarks/benchmark_runner.py
- mentat/sampler/utils.py
The motivation for this PR is a fix for the benchmark github action. Now that the benchmarks are in a different package the aren't importing mentat code from where they did previously in the file system. This change should have no effect for people calling clone_repo from the mentat root dir.
I think in general it makes sense that the caller of setup_repo would expect the repo to be places in benchmark_repos of their cwd not relative to some script that they may not know about and may be in a strange unpredictable place depending on how mentat is installed.
> Benchmark_repos specified with a relative path

- mentat/conversation.py
- mentat/parsers/git_parser.py
- mentat/revisor/revisor.py
- mentat/sampler/sampler.py
- scripts/git_log_to_transcripts.py
- scripts/sampler/finetune.py
- tests/parser_tests/git_parser_test.py
- tests/sampler_test.py
This adds the missing `GitParser.file_edits_to_llm_message` method, which we'll use to convert file edits from your conversation history into git diffs for Sampler v.0.2.0.
> add full file_edits_to_llm_message + tests

- benchmarks/arg_parser.py
- benchmarks/benchmark_runner.py
- benchmarks/benchmarks/mentat/clojure_exercism_runner.py
- benchmarks/benchmarks/mentat/license_update.py
- benchmarks/benchmarks/mentat/pre_tags.py
- benchmarks/exercism_practice.py
- mentat/sampler/utils.py
- pyproject.toml
- pyrightconfig.json
- scripts/run_and_upload_benchmarks.sh
- testbed/benchmarks/benchmarks/clojure_exercism_runner.py
- testbed/exercism-python/exercises/practice/accumulate/accumulate_test.py
- tests/benchmarks/test_benchmark_runner.py
- tests/benchmarks/test_exercism_benchmark.py
While writing this I made the following changes:
* benchmark_repos was made a subdir of benchmarks so verify functions could import from generated code. Otherwise python complains it isn't part of a module.
* In fact setup_repo does change the current directory. evalute_py and evaluate_sample now change the directory back.
* The whole functions have a try now so spurious errors won't crash a run.
* The append action is removed from the parser.
It's a little less comprehensive than the exercism analogue but I think it'll still be valuable.
> Benchmark runner test

- mentat/config.py
- mentat/session.py
It's not very safe to be messing with git at startup. There are a lot of edge cases. Most users won't use the sampler at all and even with this change the sampler will still work well assuming the changes being made aren't related to the active diff.
> Active diff snapshot not automatically run

- mentat/llm_api_handler.py
> fix azure by removing model checking

- benchmarks/arg_parser.py
- benchmarks/benchmark_result.py
- benchmarks/benchmark_runner.py
- tests/benchmarks/test_benchmark_runner.py
Changes that I made while working with samples/benchmarks.
> QOL updates from running benchmark samples

- mentat/daemon.py
Adds the file contents the `@mentat` comment is in to the user prompt.
> add code file to daemon prompt

- mentat/daemon.py
- requirements.txt
- setup.py
The Mentat Daemon is an experiment not meant to necessarily replace Mentat, but is an alternate way to interface with Mentat that may provide a better, Copilot-like DX.
The idea is that there is a background process (the Mentat Daemon) that watches a directory for file changes. When a user changes a file, the daemon calls an LLM and inserts the code into the file where the comment was.
The daemon can be started in the command line like this:
```bash
>> mentat-daemon
````
Once started, a simple TUI showing file changes and LLM progress/edits is displayed. To invoke the Mentat Daemon, the user can write comments prefixed with `@mentat` to insert LLM-generated code. For a python file, the syntax would look like this:
```python
```
After the user saves the file, the Mentat Daemon will check …
> Add Mentat Daemon

- benchmarks/edit_rubric_benchmark.py
- benchmarks/exercism_practice.py
- benchmarks/run_sample.py
- docs/source/index.rst
- docs/source/sdk/index.rst
- docs/source/sdk/module.rst
- docs/source/sdk/usage.rst
- mentat/__init__.py
- mentat/python_client/client.py
- mentat/sentry.py
- mentat/utils.py
- setup.py
- tests/diff_context_test.py
- tests/sampler_test.py
You can now import the PythonClient via `from mentat import Mentat`.
* Docs updated
* Comments added to python_client
* tests and benchmarks updated to use new import
> Python client default mentat export

- mentat/code_context.py
- mentat/diff_context.py
- mentat/git_handler.py
- mentat/terminal/client.py
- mentat/terminal/terminal_app.py
They are found with a new function which uses the --directory flag to be fast even when large directories are untracked and unignored. They are rendered in red instead of green in the ui. Unused git functions are deleted.
> Untracked files handled differently

- mentat/code_context.py
- mentat/code_feature.py
- mentat/diff_context.py
- mentat/session.py
- tests/code_context_test.py
- tests/conftest.py
- tests/diff_context_test.py
When run in a non git directory the diff context was set to null which made interacting with it complex. Now the diff context is responsible for determining it is not in a git context and returning sensible empty/none types when called.
> Diff Context never null

- mentat/agent_handler.py
- mentat/code_context.py
- mentat/conversation.py
- mentat/revisor/revisor.py
- mentat/sampler/sampler.py
- mentat/session.py
- mentat/session_input.py
- tests/code_context_test.py
- tests/commands_test.py
- tests/conversation_test.py
Frequently in the codebase people will go to conversation for the messages and then independently get the code_message. It's simpler if the conversation handles that.
get_messages is also changed to accept a system prompt argument instead of having a include_system_prompt parameter to simplify agent's calling of it. If callers genuinely want no system prompt they can pass `[]`.
Move responsibility to raise if context too big from code_context to conversation.
> Conversation get_messages gets code_message

- .github/workflows/lint_and_test.yml
- docs/source/user/commands.rst
- mentat/code_context.py
- mentat/code_feature.py
- mentat/command/commands/__init__.py
- mentat/command/commands/load.py
- mentat/command/commands/save.py
- mentat/interval.py
- mentat/session_stream.py
- tests/commands_test.py
> Add `load`/`save` context commands

- docs/source/user/alternative_models.rst
- mentat/llm_api_handler.py
System messages are converted to annotated user messages and repeated messages are concatenated.
This is sort of an ugly PR. I'd rather convert system messages to user messages natively and then have no difference between how gpt/claude are handled. I think a better philosophy than using system messages to inject information from the environment would be to tell the llm its talking to a bot that is relaying information from the end user and the environment and then have all system messages besides the parser prompt be user messages annotated with "Code message" and annotate the actual user messages as "End user message:".
But I kind of want to get this out quickly because it seems clear claude 3 is better than gpt-4 and I want to make it possible for other people to use it.
> Anthropic message normalization

- .github/workflows/lint_and_test.yml
ctags installs were failing on github actions macos runners. Switching from `macos-latest` to `macos-14` seems to fix it (although I thought 14 was the latest??)
more details here: https://github.com/actions/runner-images/issues/4020
> Fix Github Actions ctags install issue

- README.md
- benchmarks/benchmark_runner.py
- benchmarks/exercism_practice.py
- mentat/agent_handler.py
- mentat/config.py
- mentat/conversation.py
- mentat/feature_filters/llm_feature_filter.py
- mentat/llm_api_handler.py
- mentat/revisor/revisor.py
- mentat/session.py
- requirements.txt
- tests/conftest.py
> Add provider config and update spice with new models

- requirements.txt
use `~=0.1.x` to always fetch latest minor version of spiceai and ragdaemon.
> Require latest spice and ragdaemon

- mentat/code_context.py
- mentat/config.py
- mentat/llm_api_handler.py
- mentat/session.py
> Changes for 1.0.18

- tests/code_context_test.py
- tests/code_file_manager_test.py
> update test results for no tags by default

- requirements.txt
CI was failing. Looks like it was last run with ragdaemon 0.2.7. We got up to 0.2.12 and then recently switched to 0.3.0. Here I pin the version to 0.2.12 to keep it steady. If we start developing mentat again, we can bump it up.
> pin ragdaemon to the last 0.2.x version
